const musicData = [
  {
    id: 1,
    name: "Rap God",
    artist: "Eminem",
    coverSmall: "./img/rap-god-small.jpg",
    coverLarge: "./img/rap-god-large.jpg",
    source: "./audio/dont-hold-me-down.mp3",
  },
  {
    id: 2,
    name: "Starboy",
    artist: "The Weekend",
    coverSmall: "./img/starboy-small.jpg",
    coverLarge: "./img/starboy-large.jpg",
    source: "./audio/feel-alive.mp3",
  },
  {
    id: 3,
    name: "God's Plan",
    artist: "Drake",
    coverSmall: "./img/gods-plan-small.jpg",
    coverLarge: "./img/gods-plan-large.jpg",
    source: "./audio/fly-again.mp3",
  },
  {
    id: 4,
    name: "Lonely Star",
    artist: "Oh Wonder",
    coverSmall: "./img/lonely-star-small.jpg",
    coverLarge: "./img/lonely-star-large.jpg",
    source: "./audio/healing.mp3",
  },
  {
    id: 5,
    name: "Susamam",
    artist: "Saniser",
    // coverSmall: "./img/susamam-small.jpg",
    // coverLarge: "./img/susamam-large.jpg",
    source: "./audio/memory.mp3",
  },
  {
    id: 6,
    name: "Lonely",
    artist: "Kid Cudi",
    coverSmall: "./img/lonely-small.jpg",
    coverLarge: "./img/lonely-large.jpg",
    source: "./audio/need-you.mp3",
  },
  {
    id: 7,
    name: "Tossie Side",
    artist: "Drake",
    coverSmall: "./img/tossie-side-small.jpg",
    coverLarge: "./img/tossie-side-large.jpg",
    source: "./audio/rewind.mp3",
  },
  {
    id: 8,
    name: "Work",
    artist: "Rihanna",
    // coverSmall: "./img/work-small.jpg",
    // coverLarge: "./img/work-large.jpg",
    source: "./audio/time-travel.mp3",
  },
]
export default musicData
